#!/bin/bash
 
#PBS -N HiC_Correct
#PBS -l select=1:ncpus=16:mem=100gb
#PBS -l walltime=2:00:00
#PBS -j oe
#PBS -M myemailadress@generic.com
#PBS -m ae
 

module load hicexplorer/3.4.3

hicCorrectMatrix diagnostic_plot --matrix Matrix_males_500kb_bin_renamed.h5 \
-o Diagnostic_plot_males_500kb_bin.png

hicCorrectMatrix correct -m Matrix_males_500kb_bin_renamed.h5 \
--filterThreshold -1.5 3 \
-o Matrix_corrected_males_500kb_bin_-1.5_3.h5
