#!/bin/bash
 
#PBS -N HiC_plotTADs
#PBS -l select=1:ncpus=16:mem=30gb
#PBS -l walltime=1:00:00
#PBS -j oe
#PBS -M myemailadress@generic.com
#PBS -m ae

module load hicexplorer/3.4.3

input="NCBI_ornAna1.chrom.sizes"
while IFS= read -r line
do
    lines=( $line )

    hicPlotTADs --tracks HiC_plotTADs_tracks.ini \
    --out Plot_TADs_hic_and_eigen_"${lines[0]}".pdf \
    --region chr"${lines[0]}":1-"${lines[1]}" \
    --dpi 300

done < "$input"
