#!/bin/bash
 
#PBS -N HiC_SumMatrices
#PBS -l select=1:ncpus=16:mem=100gb
#PBS -l walltime=6:00:00
#PBS -j oe
#PBS -M myemailadress@generic.com
#PBS -m ae
 

module load hicexplorer/3.4.3

hicSumMatrices -m Matrix_male_5-1_500kb_bin_renamed.h5 \
Matrix_male_5-2_500kb_bin_renamed.h5 \
Matrix_male_5-3_500kb_bin_renamed.h5 \
Matrix_male_5-4_500kb_bin_renamed.h5 \
--outFileName Matrix_males_500kb_bin_renamed.h5
